language: node_js
node_js:
  - "10"

cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  - provider: script
    script: npx firebase deploy --token $FB_TOKEN
    on:
      branch: master
