language: node_js
node_js:
  - "10"

cache: npm

install:
  - npm ci

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: deploy
      script: npx firebase deploy --token $FB_TOKEN
